name: Set up QEMU
 - uses: docker/setup-qemu-action@v1

name: build wheels with manylinux2014 docker images
runs:
    using: 'docker'
    image: docker://quay.io/pypa/manylinux2014_aarch64
    args:
        - .github/workflows/entrypoint.sh
